# Outputs
monitorrule=name:HDMI-A-1,width:1680,height:1050,x:0,y:0
monitorrule=name:eDP-1,x:1680,y:0

# Input

xkb_rules_options=ctrl:nocaps
trackpad_natural_scrolling=1
tap_to_click=1

# Cursor / misc

cursor_theme=capitaine-cursors
cursor_size=24

env=XDG_CURRENT_DESKTOP,mango
env=PYTHONIOENCODING,utf-8