# Firefox ESR browser with Pywalfox native messaging and curated extensions.
#
# The pywalfox-manifest derivation is needed because Home Manager's
# nativeMessagingHosts option expects a package that exposes the manifest
# JSON at the standard path inside its output — this constructs that package
# from scratch using writeTextFile.
{ pkgs, lib, config, inputs, ... }:

let
  pywalfox-manifest = pkgs.writeTextFile {
    name = "pywalfox-manifest";
    destination = "/lib/mozilla/native-messaging-hosts/pywalfox.json";
    text = builtins.toJSON {
      name = "pywalfox";
      description = "Automatically theme your browser using the colors generated by Pywal";
      path = "${pkgs.pywalfox-native}/bin/pywalfox";
      type = "stdio";
      allowed_extensions = [ "pywalfox@frewacom.org" ];
    };
  };
in
{
  options.nixtop.apps.firefox-esr.enable = lib.mkEnableOption "Firefox ESR browser configuration";

  config = lib.mkIf config.nixtop.apps.firefox-esr.enable {
    programs.firefox = {
      enable = true;
      package = pkgs.firefox-esr;
      # configPath = "${config.xdg.configHome}/mozilla/firefox"; uncomment once june 21
      # ^ waiting for esr to shift to 153
      nativeMessagingHosts = [ pywalfox-manifest ];
      # Profile name matches the username so Firefox creates it automatically.
      profiles.${config.home.username} = {
        isDefault = true;
        extensions.packages = with inputs.firefox-addons.packages.${pkgs.stdenv.hostPlatform.system}; [
          pywalfox        # dynamic Pywal colour theming
          ublock-origin   # ad & tracker blocking
          darkreader      # automatic dark mode for any site
          bitwarden       # password manager
          sponsorblock    # skip YouTube sponsor segments
        ];
        settings = {
          # autoDisableScopes=0 prevents Firefox from silently disabling
          # declaratively installed extensions on first launch.
          "extensions.autoDisableScopes" = 0;
          # enabledScopes=15 (all bits set) ensures all scope types are active.
          "extensions.enabledScopes" = 15;
        };
      };
    };

    # pywalfox-native provides the host binary the manifest points at.
    home.packages = [ pkgs.pywalfox-native ];
  };
}

