{ pkgs, lib, config, inputs, ... }:

let
  pywalfox-manifest = pkgs.writeTextFile {
    name = "pywalfox-manifest";
    destination = "/lib/mozilla/native-messaging-hosts/pywalfox.json";
    text = builtins.toJSON {
      name = "pywalfox";
      description = "Automatically theme your browser using the colors generated by Pywal";
      path = "${pkgs.pywalfox-native}/bin/pywalfox";
      type = "stdio";
      allowed_extensions = [ "pywalfox@frewacom.org" ];
    };
  };
in
{
  options.nixtop.apps.firefox-esr.enable = lib.mkEnableOption "Firefox ESR browser configuration";

  config = lib.mkIf config.nixtop.apps.firefox-esr.enable {
    programs.firefox = {
      enable = true;
      package = pkgs.firefox-esr;
      nativeMessagingHosts = [ pywalfox-manifest ];
      profiles.${config.home.username} = {
        isDefault = true;
        extensions.packages = with inputs.firefox-addons.packages.${pkgs.stdenv.hostPlatform.system}; [
          pywalfox
          ublock-origin
          darkreader
          bitwarden
          sponsorblock
        ];
        settings = {
          "extensions.autoDisableScopes" = 0;
          "extensions.enabledScopes" = 15;
        };
      };
    };

    home.packages = [ pkgs.pywalfox-native ];
  };
}

