# Layer
layerrule=noblur:1,layer_name:rexies.notch.quickshell
layerrule=noblur:1,layer_name:rexies.notch.pseudotop
layerrule=noblur:1,layer_name:nagare-dock
layerrule=noblur:1,layer_name:nagare-volume-osd
layerrule=noblur:1,layer_name:nagare-launcher
layerrule=noblur:1,layer_name:nagare-netpanel
layerrule=noblur:1,layer_name:nagare-quickoptions
layerrule=noblur:1,layer_name:nagare-polkit

# Window
windowrule=appid:^(eog|sxiv|feh|mpv|vlc|file-roller|xarchiver|loupe)$,isfloating:1
windowrule=appid:^org\.gnome\.Nautilus$,title:.*Progress.*,isfloating:1
windowrule=appid:^org\.gnome\.Nautilus$,title:.*Replace.*,isfloating:1
