#!/bin/sh
set -eu
dir="${XDG_PICTURES_DIR:-$HOME/Pictures}/Screenshots"
mkdir -p "$dir"
file="$dir/region-$(date +%Y-%m-%d_%H-%M-%S).png"
grim -g "$(slurp)" "$file"
notify-send -i "$file" 'Screenshot saved' "$file"

