#!/usr/bin/env bash
# Auto-generated by matugen — do not edit directly
PRIMARY_LIGHT="#63568f"
PRIMARY_DARK="#cdbdff"
SECONDARY_LIGHT="#615b71"
SECONDARY_DARK="#cbc3dc"
TERTIARY_LIGHT="#7d5261"
TERTIARY_DARK="#eeb8ca"
