# Shared sway variables. $wallpaper must exist in ~/Pictures/Wallpapers.
set $mod Mod1
set $term foot
set $menu fuzzel
set $wallpaper ~/Pictures/Wallpapers/serial_experiments_lain_server_room.png
set $scripts ~/.config/sway/scripts
set $lock swaylock -C ~/.config/swaylock/config
