# Variables — edit your mod, terminal and paths here
set $mod Mod1
set $term foot
set $menu fuzzel
set $wallpaper ~/Pictures/Wallpapers/alpine-lake.jpg
set $scripts ~/.config/sway/scripts
set $lock swaylock -C ~/.config/swaylock/config
