#!/usr/bin/env bash
# Auto-generated by matugen — do not edit directly
PRIMARY_LIGHT="#8f4c32"
PRIMARY_DARK="#ffb59a"
SECONDARY_LIGHT="#77574c"
SECONDARY_DARK="#e7beaf"
TERTIARY_LIGHT="#695e30"
TERTIARY_DARK="#d5c78e"
