#!/usr/bin/env bash
# Auto-generated by matugen — do not edit directly
PRIMARY_LIGHT="#894a67"
PRIMARY_DARK="#ffb0d1"
SECONDARY_LIGHT="#735762"
SECONDARY_DARK="#e1bdca"
TERTIARY_LIGHT="#7e5538"
TERTIARY_DARK="#f1bb98"
