#!/usr/bin/env bash
# Auto-generated by matugen — do not edit directly
PRIMARY_LIGHT="{{colors.primary.light.hex}}"
PRIMARY_DARK="{{colors.primary.dark.hex}}"
SECONDARY_LIGHT="{{colors.secondary.light.hex}}"
SECONDARY_DARK="{{colors.secondary.dark.hex}}"
TERTIARY_LIGHT="{{colors.tertiary.light.hex}}"
TERTIARY_DARK="{{colors.tertiary.dark.hex}}"
