blur enable
blur_passes 2
blur_radius 5
blur_xray enable

corner_radius 0
default_dim_inactive 0.08
shadows enable
shadow_blur_radius 15
shadow_color #00000055

layer_effects "mako" blur enable; corner_radius 8; shadows enable
# layer_effects "waybar" blur enable; corner_radius 0; shadows enable
layer_effects "wofi" blur enable; corner_radius 12; shadows enable
layer_effects "swaynag" blur enable; corner_radius 8; shadows enable
