[colors]
background=101418
foreground=e1e2e8

## Normal colors
regular0=32353a
regular1=ffb4ab
regular2=9fcafc
regular3=d6bee5
regular4=bac8db
regular5=174974
regular6=524060
regular7=e1e2e8

## Bright colors
bright0=8c9199
bright1=93000a
bright2=d0e4ff
bright3=f1daff
bright4=d6e4f7
bright5=d0e4ff
bright6=34618e
bright7=c2c7cf