[main]
include=~/.config/foot/themes/flutterice
font=Courier Prime:size=11
shell=/usr/bin/zsh
# Noctalia can write a theme include here; empty file is fine until then
include=~/.config/foot/colors.ini

[colors]
alpha=0.8
