#!/usr/bin/env bash
# Auto-generated by matugen — do not edit directly
PRIMARY_LIGHT="#00677e"
PRIMARY_DARK="#5bd5fa"
SECONDARY_LIGHT="#04677e"
SECONDARY_DARK="#87d1eb"
TERTIARY_LIGHT="#4b5c92"
TERTIARY_DARK="#b4c5ff"
