#!/usr/bin/env bash
# Auto-generated by matugen — do not edit directly
PRIMARY_LIGHT="#5256a9"
PRIMARY_DARK="#c0c1ff"
SECONDARY_LIGHT="#575992"
SECONDARY_DARK="#c0c1ff"
TERTIARY_LIGHT="#7f4d7a"
TERTIARY_DARK="#f0b3e7"
