#!/usr/bin/env bash
# Auto-generated by matugen — do not edit directly
PRIMARY_LIGHT="#884588"
PRIMARY_DARK="#fbacf7"
SECONDARY_LIGHT="#7e4e7c"
SECONDARY_DARK="#eeb4e9"
TERTIARY_LIGHT="#904a47"
TERTIARY_DARK="#ffb3af"
