;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ewm-frame-right
        ewm-frame-select
        mouse-set-region
        widget-forward
        ))

(setq mc/cmds-to-run-once
      '(
        undefined
        widget-forward
        ))
