{
  pkgs,
  lib,
  config,
  ...
}:
let
  pywalfox-manifest = pkgs.writeTextFile {
    name = "pywalfox-manifest";
    destination = "/lib/mozilla/native-messaging-hosts/pywalfox.json";
    text = builtins.toJSON {
      name = "pywalfox";
      description = "Automatically theme your browser using the colors generated by Pywal";
      path = "${pkgs.pywalfox-native}/bin/pywalfox";
      type = "stdio";
      allowed_extensions = [ "pywalfox@frewacom.org" ];
    };
  };
in
{
  options.nixtop.apps.firefox.enable = lib.mkEnableOption "Firefox browser configuration";

  config = lib.mkIf config.nixtop.apps.firefox.enable {
    programs.firefox = {
      enable = true;
      package = pkgs.firefox;
      configPath = "${config.xdg.configHome}/mozilla/firefox";
      nativeMessagingHosts = [ pywalfox-manifest ];
      policies.ExtensionSettings = {
        "uBlock0@raymondhill.net" = {
          installation_mode = "force_installed";
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi";
        };
        "addon@darkreader.org" = {
          installation_mode = "force_installed";
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/darkreader/latest.xpi";
        };
        "{446900e4-71c2-419f-a6a7-df9c091e268b}" = {
          installation_mode = "force_installed";
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/bitwarden-password-manager/latest.xpi";
        };
        "sponsorBlocker@ajay.app" = {
          installation_mode = "force_installed";
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/sponsorblock/latest.xpi";
        };
      };
      profiles.${config.home.username} = {
        isDefault = true;
        settings = {
          "extensions.autoDisableScopes" = 0;
          "extensions.enabledScopes" = 15;
        };
      };
    };
    home.packages = [ pkgs.pywalfox-native ];
  };
}
