{ config, lib, pkgs, inputs, ... }:
let
  cfg = config.nixtop.noctalia or { enable = true; };
  shell = if config ? osConfig then config.osConfig.nixtop.shell else config.nixtop.shell or "noctalia";
  shellEnabled = shell == "noctalia";
in
{
  options.nixtop.noctalia.enable = lib.mkOption {
    type = lib.types.bool;
    default = shellEnabled;
    description = "Enable Noctalia shell (follows nixtop.shell when auto).";
  };

  config = lib.mkIf (cfg.enable && shellEnabled) {
    # Noctalia shell is provided by the flake's homeManagerModule (imported globally via flake.nix).
    # Here we set the palette bridge and basic settings.
    # The palette file is generated by matugen to ~/.config/noctalia/palettes/nixtop.json
    xdg.configFile."noctalia/settings.toml".text = lib.mkAfter ''
      [theme]
      source = "custom"
      custom_palette = "nixtop"
    '';

    # Ensure Noctalia's template catalog is enabled (network allowed)
    # Noctalia's own settings.toml manages this; we just ensure the directory exists.
    home.activation.ensureNoctaliaDir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      $DRY_RUN_CMD mkdir -p "$HOME/.config/noctalia"
      $DRY_RUN_CMD mkdir -p "$HOME/.config/noctalia/palettes"
    '';

    # Assert mutual exclusion with quickshell
    assertions = [
      {
        assertion = !(config.nixtop.quickshell.enable or false);
        message = "nixtop.shell selects one shell – cannot enable both noctalia and quickshell";
      }
    ];
  };
}
