{ config, lib, pkgs, inputs, ... }:
let
  cfg = config.nixtop.noctalia or { enable = true; };
  shell = if config ? osConfig then config.osConfig.nixtop.shell else config.nixtop.shell or "noctalia";
  shellEnabled = shell == "noctalia";
in
{
  imports = (if inputs.noctalia-shell ? homeModules
    then builtins.attrValues inputs.noctalia-shell.homeModules
    else if inputs.noctalia-shell ? homeManagerModules
    then builtins.attrValues inputs.noctalia-shell.homeManagerModules
    else []);

  options.nixtop.noctalia.enable = lib.mkOption {
    type = lib.types.bool;
    default = shellEnabled;
    description = "Enable Noctalia shell (follows nixtop.shell when auto).";
  };

  config = lib.mkIf (cfg.enable && shellEnabled) {
    programs.noctalia = {
      enable = true;
      # Noctalia v5 – use custom palette generated by matugen (nixtop.json)
      # and enable Mango integration. The palette file is at
      # ~/.config/noctalia/palettes/nixtop.json (matugen bridge).
      settings = {
        # theme bridge – §8.2
        theme.source = "custom";
        theme.custom_palette = "nixtop";
        # Mango compositor – Noctalia will generate its Mango appearance
        # via its own templates when this is set correctly.
        # Keep template catalog enabled (network allowed) – don't filter it.
        # The old noctaniri set builtin_ids = [ "niri" ]; for Mango we leave
        # it to Noctalia's defaults which already include Mango when detected.
      };
    };

    # Ensure palette dir exists before first matugen run (matugen writes nixtop.json)
    home.activation.ensureNoctaliaDir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      $DRY_RUN_CMD mkdir -p "$HOME/.config/noctalia"
      $DRY_RUN_CMD mkdir -p "$HOME/.config/noctalia/palettes"
    '';

    # Also set the settings.toml via HM is handled by programs.noctalia above;
    # the xdg.configFile fallback is not needed when using the HM module.
    # Keep the assertion for mutual exclusion.
    assertions = [
      {
        assertion = !(config.nixtop.quickshell.enable or false);
        message = "nixtop.shell selects one shell – cannot enable both noctalia and quickshell";
      }
    ];
  };
}
