{
  config,
  lib,
  pkgs,
  inputs,
  osConfig ? null,
  ...
}:
let
  cfg = config.nixtop.noctalia;
  # Per-user shell (modules/shell): host default, overridable per user.
  shell = config.nixtop.shell;
  shellEnabled = shell == "noctalia";
  # swayfx is the primary compositor now; mango is archived. Noctalia supports both.
  compositor = cfg.compositor or "sway";
in
{
  imports = (
    if inputs.noctalia-shell ? homeModules then
      builtins.attrValues inputs.noctalia-shell.homeModules
    else if inputs.noctalia-shell ? homeManagerModules then
      builtins.attrValues inputs.noctalia-shell.homeManagerModules
    else
      [ ]
  );

  options.nixtop.noctalia.enable = lib.mkOption {
    type = lib.types.bool;
    default = shellEnabled;
    description = "Enable Noctalia shell (follows nixtop.shell when auto; swayfx primary, mango archived).";
  };
  options.nixtop.noctalia.compositor = lib.mkOption {
    type = lib.types.enum [
      "sway"
      "mango"
    ];
    default = "sway";
    description = ''
      Which compositor session Noctalia runs in. "sway" autostarts it from the
      swayfx config; "mango" leaves sway alone and relies on the mango
      session's own autostart (modules/mango/variants/noctalia/).
    '';
  };

  config = lib.mkIf (cfg.enable && shellEnabled) {
    programs.noctalia = {
      enable = true;
      # Noctalia v5 – use custom palette generated by matugen (nixtop.json)
      # The palette file is at ~/.config/noctalia/palettes/nixtop.json (matugen bridge).
      # Noctalia-side settings are identical for sway and mango: both
      # compositors draw their own shadows, so Noctalia's stay off (per the
      # mango docs), and the palette bridge is compositor-independent.
      # The compositor choice only changes who autostarts Noctalia — see
      # modules/sway/default.nix (sway) and modules/mango/variants/noctalia/ (mango).
      settings = {
        theme.source = "custom";
        theme.custom_palette = "nixtop";
        # Mango follows Noctalia: this user template re-renders mango's colors
        # from the live palette on every theme change (Noctalia's engine, not
        # matugen — same {{ }} expressions as the matugen twin). post_hook
        # mirrors the matugen registry's mango reload.
        theme.templates.user.mango = {
          input_path = "$XDG_CONFIG_HOME/noctalia/templates/mango.conf";
          output_path = "$XDG_STATE_HOME/nixtop/theme/mango.conf";
          post_hook = "mmsg dispatch reload_config 2>/dev/null || true";
        };
        # Starship follows Noctalia the same way (same twin pattern as mango).
        # No post_hook: starship re-reads its config before every prompt.
        theme.templates.user.starship = {
          input_path = "$XDG_CONFIG_HOME/noctalia/templates/starship.toml";
          output_path = "$XDG_CONFIG_HOME/starship.toml";
        };
        bar."default".shadow = false;
        bar."default".contact_shadow = false;
        dock.shadow = false;
        shell.panel.shadow = false;
      };
    };

    # User template inputs above (static — Noctalia only ever writes outputs).
    xdg.configFile."noctalia/templates/mango.conf".source = ./templates/mango.conf;
    xdg.configFile."noctalia/templates/starship.toml".source = ./templates/starship.toml;

    # Noctalia owns mango's colors and the starship prompt now, so matugen
    # must not also write them (two writers, two palettes). Stays overridable
    # per template.
    nixtop.services.matugen.templates.mango.enable = lib.mkDefault false;
    nixtop.services.matugen.templates.starship.enable = lib.mkDefault false;

    # Ensure palette dir exists before first matugen run (matugen writes nixtop.json)
    home.activation.ensureNoctaliaDir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      $DRY_RUN_CMD mkdir -p "$HOME/.config/noctalia"
      $DRY_RUN_CMD mkdir -p "$HOME/.config/noctalia/palettes"
    '';

    assertions = [
      {
        assertion = !(config.nixtop.quickshell.enable or false);
        message = "nixtop.shell selects one shell – cannot enable both noctalia and quickshell";
      }
      {
        assertion = !(config.nixtop.jes.enable or false);
        message = "nixtop.shell selects one shell – cannot enable both noctalia and jes";
      }
      {
        assertion = !(config.nixtop.lucid.enable or false);
        message = "nixtop.shell selects one shell – cannot enable both noctalia and lucid";
      }
      {
        assertion = compositor == "sway" || compositor == "mango";
        message = "nixtop.noctalia.compositor must be sway (primary) or mango (archived)";
      }
    ];
  };
}
