# Wires kurukurubar's greeter.qml into services.greetd. Used to be
# flutterquick's own `nixosModules.greeter` - folded in here now that
# flutterquick's source lives at modules/home/themes/kurukuru/quickshell
# instead of a separate flake input. Deliberately does NOT own: the
# `greeter` user (greetd's own package/module already provisions one,
# hosts/common/default.nix further customizes its $HOME), or
# wallpaper/config seeding for that user (also hosts/common/default.nix).
{ lib, pkgs, config, inputs, ... }:
let
  cfg = config.programs.kurukurubar.greeter;
  system = pkgs.stdenv.hostPlatform.system;
  kurukurubar = import ../home/themes/kurukuru/package.nix {
    inherit pkgs;
    quickshellInput = inputs.quickshell;
  };
  greeterBin = "${kurukurubar}/bin/kurukurubar-greeter";

  # kurukurubar-greeter's own QML wallpaper loading works fine (verified
  # via KURU_GREETER_MOCK=1) but never actually shows a background inside
  # the real greetd/`/var/lib/greeter` session - the failure is specific
  # to that runtime environment, not the QML/config wiring, which has
  # already been fixed twice (file:// URL, stale-config r!). Rather than
  # keep guessing at the greetd-environment cause, fall back to swaybg as
  # a second, independent layer-background - same pattern already used
  # for the noctaniri theme (modules/home/themes/noctaniri/niri/default.nix).
  # If kurukurubar-greeter's own wallpaper ever starts rendering, this
  # just sits underneath it unnoticed.
  greeterWallpaper = "${inputs.self}/assets/wallpaper/serial_experiments_lain_server_room.jpg";

  niriGreeterConf = pkgs.writeText "niri-greeter.kdl" ''
    // Generated by modules/nixos/kurukuru-greeter.nix - greeter-session-only
    // config, NOT your real ~/.config/niri/config.kdl.
    spawn-at-startup "${lib.getExe pkgs.swaybg}" "-i" "${greeterWallpaper}" "-m" "fill"
    spawn-at-startup "${greeterBin}"
    input {
    }
  '';

  labwcGreeterConf = pkgs.runCommand "labwc-greeter-dir" {} ''
    mkdir -p $out
    cat > $out/autostart <<EOF
    ${greeterBin} &
    EOF
  '';
in
{
  options.programs.kurukurubar.greeter = {
    enable = lib.mkEnableOption "greetd session running kurukurubar's greeter.qml";
    compositor = lib.mkOption {
      type = lib.types.enum [ "niri" "labwc" ];
      default = "niri";
      description = "Which compositor runs the greeter session itself. Independent of what your real post-login session uses.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.greetd = {
      enable = true;
      settings.terminal.vt = 1;
      settings.default_session = {
        user = "greeter";
        command =
          if cfg.compositor == "niri"
          then "${lib.getExe pkgs.niri} --config ${niriGreeterConf}"
          else "${lib.getExe' pkgs.labwc "labwc"} -C ${labwcGreeterConf}";
      };
    };
  };
}
