# Wires kurukurubar's greeter.qml into services.greetd. Used to be
# flutterquick's own `nixosModules.greeter` - folded in here now that
# flutterquick's source lives at modules/home/themes/kurukuru/quickshell
# instead of a separate flake input. Deliberately does NOT own: the
# `greeter` user (greetd's own package/module already provisions one,
# hosts/common/default.nix further customizes its $HOME), or
# wallpaper/config seeding for that user (also hosts/common/default.nix).
{ lib, pkgs, config, inputs, ... }:
let
  cfg = config.programs.kurukurubar.greeter;
  system = pkgs.stdenv.hostPlatform.system;
  kurukurubar = import ../home/themes/kurukuru/package.nix {
    inherit pkgs;
    quickshellInput = inputs.quickshell;
  };
  greeterBin = "${kurukurubar}/bin/kurukurubar-greeter";

  niriGreeterConf = pkgs.writeText "niri-greeter.kdl" ''
    // Generated by modules/nixos/kurukuru-greeter.nix - greeter-session-only
    // config, NOT your real ~/.config/niri/config.kdl.
    spawn-at-startup "${greeterBin}"
    input {
    }
  '';

  labwcGreeterConf = pkgs.runCommand "labwc-greeter-dir" {} ''
    mkdir -p $out
    cat > $out/autostart <<EOF
    ${greeterBin} &
    EOF
  '';
in
{
  options.programs.kurukurubar.greeter = {
    enable = lib.mkEnableOption "greetd session running kurukurubar's greeter.qml";
    compositor = lib.mkOption {
      type = lib.types.enum [ "niri" "labwc" ];
      default = "niri";
      description = "Which compositor runs the greeter session itself. Independent of what your real post-login session uses.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.greetd = {
      enable = true;
      settings.terminal.vt = 1;
      settings.default_session = {
        user = "greeter";
        command =
          if cfg.compositor == "niri"
          then "${lib.getExe pkgs.niri} --config ${niriGreeterConf}"
          else "${lib.getExe' pkgs.labwc "labwc"} -C ${labwcGreeterConf}";
      };
    };
  };
}
